development:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] ? ENV['POSTGRES_HOST'] : '/var/run/postgresql' %>
  username: <%= ENV['POSTGRES_USER'] ? ENV['POSTGRES_USER'] : 'envizon' %>
  password: <%= ENV['POSTGRES_PASSWORD'] ? ENV['POSTGRES_PASSWORD'] : 'envizon' %>
  database: <%= ENV['POSTGRES_DB'] ? ENV['POSTGRES_DB'] : 'envizon' %>

test:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] ? ENV['POSTGRES_HOST'] : '/var/run/postgresql' %>
  username: <%= ENV['POSTGRES_USER'] ? ENV['POSTGRES_USER'] : 'envizon' %>
  password: <%= ENV['POSTGRES_PASSWORD'] ? ENV['POSTGRES_PASSWORD'] : 'envizon' %>
  database: <%= ENV['POSTGRES_TEST_DB'] ? ENV['POSTGRES_TEST_DB'] : 'envizon_test' %>

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] ? ENV['POSTGRES_HOST'] : '/var/run/postgresql' %>
  username: <%= ENV['POSTGRES_USER'] ? ENV['POSTGRES_USER'] : 'envizon' %>
  password: <%= ENV['POSTGRES_PASSWORD'] ? ENV['POSTGRES_PASSWORD'] : 'envizon' %>
  database: <%= ENV['POSTGRES_PRODUCTION_DB'] ? ENV['POSTGRES_PRODUCTION_DB'] : 'envizon' %>
